---
- name: VPN | Configuration | Copy easy-rsa scripts
  command: "rsync -avi /usr/share/easy-rsa /etc/openvpn"
  args:
    creates: /etc/openvpn/easy-rsa/build-ca

- name: VPN | Configuration | Create link to openssl config
  file:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    state: link

- name: VPN | Configuration | Change default CRL list time
  lineinfile:
    path: /etc/openvpn/easy-rsa/openssl.cnf
    regexp: '^default_crl_days'
    line: 'default_crl_days=3650'
    insertafter: '^default_days'

- name: VPN | Configuration | Create easy-rsa vars
  template:
    src: easy_rsa_vars
    dest: /etc/openvpn/easy-rsa/vars

- name: VPN | Configuration | Create keys dir
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
