---
- name: VPN | Checks | Check provided options
  import_tasks: _prechecks.yml
  tags: ['checks']

- name: VPN | Installation | Prepare OpenVPN repo and install server
  import_tasks: setup_openvpn_server.yml
  tags: ['openvpn_config']

- name: VPN | Installation | Prepare easy-rsa scripts
  import_tasks: easy_rsa_prepare.yml
  tags: ['easy_rsa_prepare']

- name: VPN | Installation | Prepare system to be ready to be OpenVPN server
  import_tasks: system_prepare.yml
  tags: ['system_prepare']

- name: VPN | Keys creation | Generate server keys
  import_tasks: setup_server_keys.yml
  tags: ['server_keys']

- name: VPN | Users | Ensure given users on server
  include_tasks: create_openvpn_user.yml
  loop: "{{ clients }}"
  loop_control:
    loop_var: user
  tags:
    - create_users
    - openvpn_users
    - send_mails

- name: VPN | Configuration | Check if CRL file exists
  stat:
    path: /etc/openvpn/easy-rsa/keys/crl.pem
  register: crl_file
  tags:
    - openvpn_config
    - revoke_users
    - openvpn_users

- name: VPN | Users | Revoke not listed users on server
  import_tasks: remove_openvpn_users.yml
  tags:
    - revoke_users
    - openvpn_users

- name: VPN | Configuration | Check if CRL file exists
  stat:
    path: /etc/openvpn/easy-rsa/keys/crl.pem
  register: crl_file
  tags: ['openvpn_config']

- name: VPN | Configuration | Ensure main config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'openvpn.conf', dest: '/etc/openvpn/openvpn.conf' }
  notify:
    - Restart OpenVPN
  tags: ['openvpn_config']
