---
- name: VPN | Installation | Add official OpenVPN apt key
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present

- name: VPN | Installation | Add official OpenVPN repository
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/stable xenial main
    state: present

- name: VPN | Installation | Install latest version of OpenVPN server
  package:
    name: openvpn
    state: latest

- name: VPN | Installation | Install additional packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - easy-rsa
    - iptables-persistent

- name: VPN | Configuration | Ensure main config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'openvpn.conf', dest: '/etc/openvpn/openvpn.conf' }
  notify:
    - Restart OpenVPN
