---
- name: VPN | Keys creation | Create keys directory
  file:
    path: /etc/openvpn/server_keys
    state: directory

- name: VPN | Import pre-focal tasks
  include_tasks: "setup_server_keys_{{ ansible_distribution_release|lower }}.yml"

- name: VPN | Keys creation | Create tls-auth key
  command: openvpn --genkey --secret ta.key
  args:
    chdir: /etc/openvpn/server_keys
    creates: /etc/openvpn/server_keys/ta.key
