---
- name: VPN | Installation | Add official OpenVPN apt key
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present
  when: ansible_distribution_version == '16.04'

- name: VPN | Installation | Add official OpenVPN repository
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/stable xenial main
    state: present
  when: ansible_distribution_version == '16.04'

- name: VPN | Installation | Install latest version of OpenVPN server
  package:
    name: openvpn
    state: latest
  when: ansible_distribution_version == '16.04'

- name: VPN | Installation | Install latest version of OpenVPN server
  package:
    name: openvpn
    state: latest
  when: ansible_distribution_version == '18.04'

- name: VPN | Installation | Install additional packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - easy-rsa
    - iptables-persistent

- name: VPN | Configuration | Ensure client config dif
  file:
    state: directory
    path: "{{ client_config_dir_path }}"
    mode: 0755
    owner: root
    group: root
